In [ ]:
! conda install tensorflow

  Using cached tensorflow-2.12.0-cp39-cp39-win_amd64.whl (1.9 kB)
  Using cached tensorflow_intel-2.12.0-cp39-cp39-win_amd64.whl (272.8 MB)
  Using cached tensorflow_estimator-2.12.0-py2.py3-none-any.whl (440 kB)
  Using cached tensorboard-2.12.1-py3-none-any.whl (5.6 MB)
  Using cached termcolor-2.2.0-py3-none-any.whl (6.6 kB)
  Using cached libclang-16.0.0-py2.py3-none-win_amd64.whl (24.4 MB)
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
  Using cached jax-0.4.8-py3-none-any.whl
  Using cached keras-2.12.0-py2.py3-none-any.whl (1.7 MB)
  Using cached grpcio-1.53.0-cp39-cp39-win_amd64.whl (4.0 MB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached absl_py-1.4.0-py3-none-any.whl (126 kB)
  Using cached flatbuffers-23.3.3-py2.py3-none-any.whl (26 kB)
  Using cached protobuf-4.22.1-cp39-cp39-win_amd64.whl (420 kB)
  Using cached tensorflow_io_gcs_filesystem-0.31.0-cp39-cp39-win_amd64.whl (1.5 MB)
  Us

#### Install Tensorflow

In [1]:
import tensorflow as tf

#### 1. Print Version Number of Tensorflow

In [2]:
tf.__version__

'2.12.0'

#### 2. Build a basic Convolutional Network on any past dataset we used in class (i.e. Titanic or Census Income).  Use the %%time cell magic to see how long it takes to run.

Next week we will focus on building better models.  Just get one to run this week.

In [54]:
import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [55]:

iris_data = load_iris() # load the iris dataset

print('Example data: ')
print(iris_data.data[:5])
print('Example labels: ')
print(iris_data.target[:5])

Example data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Example labels: 
[0 0 0 0 0]


In [56]:
x = iris_data.data
y_ = iris_data.target.reshape(-1, 1) # Convert data to a single column

# One Hot encode the class labels
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y_)

In [57]:
# Split the data for training and testing
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.20)


In [58]:
# Build the model

model = Sequential()

model.add(Dense(10, input_shape=(4,), activation='relu', name='fc1'))
model.add(Dense(10, activation='relu', name='fc2'))
model.add(Dense(3, activation='softmax', name='output'))

In [59]:
# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())


Neural Network Model Summary: 
Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 fc1 (Dense)                 (None, 10)                50        
                                                                 
 fc2 (Dense)                 (None, 10)                110       
                                                                 
 output (Dense)              (None, 3)                 33        
                                                                 
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________
None


C:\Users\khalil\anaconda3\lib\site-packages\keras\optimizers\legacy\adam.py:117: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super().__init__(name, **kwargs)


In [60]:
# Train the model
model.fit(train_x, train_y, verbose=2, batch_size=5, epochs=200)


Epoch 1/200
24/24 - 3s - loss: 0.8890 - accuracy: 0.4750 - 3s/epoch - 107ms/step
Epoch 2/200
24/24 - 0s - loss: 0.8397 - accuracy: 0.3833 - 57ms/epoch - 2ms/step
Epoch 3/200
24/24 - 0s - loss: 0.8174 - accuracy: 0.4250 - 39ms/epoch - 2ms/step
Epoch 4/200
24/24 - 0s - loss: 0.7900 - accuracy: 0.3917 - 46ms/epoch - 2ms/step
Epoch 5/200
24/24 - 0s - loss: 0.7556 - accuracy: 0.4250 - 49ms/epoch - 2ms/step
Epoch 6/200
24/24 - 0s - loss: 0.7133 - accuracy: 0.4417 - 44ms/epoch - 2ms/step
Epoch 7/200
24/24 - 0s - loss: 0.6765 - accuracy: 0.6750 - 44ms/epoch - 2ms/step
Epoch 8/200
24/24 - 0s - loss: 0.6461 - accuracy: 0.8167 - 38ms/epoch - 2ms/step
Epoch 9/200
24/24 - 0s - loss: 0.6072 - accuracy: 0.8083 - 43ms/epoch - 2ms/step
Epoch 10/200
24/24 - 0s - loss: 0.5733 - accuracy: 0.8250 - 43ms/epoch - 2ms/step
Epoch 11/200
24/24 - 0s - loss: 0.5449 - accuracy: 0.8500 - 44ms/epoch - 2ms/step
Epoch 12/200
24/24 - 0s - loss: 0.5145 - accuracy: 0.9000 - 44ms/epoch - 2ms/step
Epoch 13/200
24/24 - 0s -

In [61]:
# Test on unseen data

results = model.evaluate(test_x, test_y)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

1/1 [==============================] - 0s 298ms/step - loss: 0.1098 - accuracy: 0.9333
Final test set loss: 0.109835
Final test set accuracy: 0.933333


#### 3. Build a model using the mlens superlearner library from last week.  How does the accuracy compare to the barebones CNN you did above?

In [6]:
import statsmodels.api as sm
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import GradientBoostingClassifier

import xgboost as xgb
from xgboost.sklearn import XGBClassifier

import pandas
from sklearn.svm import SVC
import sklearn

from sklearn.model_selection import train_test_split

In [62]:
col_names = ["Id", "SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm","Species"]
df = pandas.read_csv(r'C:\Users\khalil\ML Lab 4\Iris.csv')
df.columns=col_names
df.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [63]:
from sklearn.preprocessing import LabelEncoder
df1=df.copy() 
df1=df1.apply(LabelEncoder().fit_transform)
df1.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
145  145             24             9             28            19        2
146  146             20             4             26            15        2
147  147             22             9             28            16        2
148  148             19            13             30            19        2
149  149             16             9             27            14        2

In [64]:
x1 = df1.drop(columns='Species')
y1 = df1['Species']
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size=0.25, random_state=555, stratify=y1)

In [65]:
%%time
LR  = LogisticRegression(solver='lbfgs', max_iter=10000, random_state=555)
RF  = RandomForestClassifier(n_estimators = 100, random_state=555)
clfs = []
print('5-fold cross validation:\n')
for clf, label in zip([LR,RF], ['Logistic Regression','Random Forest',]):
    scores = sklearn.model_selection.cross_val_score(clf, x1_train, y1_train, cv=5, scoring="accuracy")
    print("Train CV Accuracy: %0.3f (+/- %0.3f) [%s]" % (scores.mean(), scores.std(), label))
    md = clf.fit(x1_train, y1_train)
    clfs.append(md)
    print("Test Accuracy: %0.4f " % (sklearn.metrics.accuracy_score(clf.predict(x1_test), y1_test)))

5-fold cross validation:

Train CV Accuracy: 0.991 (+/- 0.018) [Logistic Regression]
Test Accuracy: 1.0000 
Train CV Accuracy: 0.991 (+/- 0.018) [Random Forest]
Test Accuracy: 1.0000 
Wall time: 1.91 s


In [66]:
from mlens.ensemble import SuperLearner
from mlens.model_selection import Evaluator
from mlens.metrics import make_scorer

from sklearn.metrics import accuracy_score

In [67]:
ensemble = SuperLearner(scorer=accuracy_score, random_state=555, verbose=2)

In [68]:
ensemble.add([RF, LR])

SuperLearner(array_check=None, backend=None, folds=2,
       layers=[Layer(backend='threading', dtype=<class 'numpy.float32'>, n_jobs=-1,
   name='layer-1', propagate_features=None, raise_on_exception=True,
   random_state=4782, shuffle=False,
   stack=[Group(backend='threading', dtype=<class 'numpy.float32'>,
   indexer=FoldIndex(X=None, folds=2, raise_on_ex...DA5C550>)],
   n_jobs=-1, name='group-2', raise_on_exception=True, transformers=[])],
   verbose=1)],
       model_selection=False, n_jobs=None, raise_on_exception=True,
       random_state=555, sample_size=20,
       scorer=<function accuracy_score at 0x0000029BBDA5C550>,
       shuffle=False, verbose=2)

In [69]:
ensemble.add_meta(GradientBoostingClassifier())

SuperLearner(array_check=None, backend=None, folds=2,
       layers=[Layer(backend='threading', dtype=<class 'numpy.float32'>, n_jobs=-1,
   name='layer-1', propagate_features=None, raise_on_exception=True,
   random_state=4782, shuffle=False,
   stack=[Group(backend='threading', dtype=<class 'numpy.float32'>,
   indexer=FoldIndex(X=None, folds=2, raise_on_ex...DA5C550>)],
   n_jobs=-1, name='group-3', raise_on_exception=True, transformers=[])],
   verbose=1)],
       model_selection=False, n_jobs=None, raise_on_exception=True,
       random_state=555, sample_size=20,
       scorer=<function accuracy_score at 0x0000029BBDA5C550>,
       shuffle=False, verbose=2)

In [70]:
ensemble.fit(x1_train, y1_train)


Fitting 2 layers
Processing layer-1             done | 00:00:00
Processing layer-2             done | 00:00:00
Fit complete                        | 00:00:01


SuperLearner(array_check=None, backend=None, folds=2,
       layers=[Layer(backend='threading', dtype=<class 'numpy.float32'>, n_jobs=-1,
   name='layer-1', propagate_features=None, raise_on_exception=True,
   random_state=4782, shuffle=False,
   stack=[Group(backend='threading', dtype=<class 'numpy.float32'>,
   indexer=FoldIndex(X=None, folds=2, raise_on_ex...DA5C550>)],
   n_jobs=-1, name='group-3', raise_on_exception=True, transformers=[])],
   verbose=1)],
       model_selection=False, n_jobs=None, raise_on_exception=True,
       random_state=555, sample_size=20,
       scorer=<function accuracy_score at 0x0000029BBDA5C550>,
       shuffle=False, verbose=2)

In [71]:
print ("Accuracy - Train : ", sklearn.metrics.accuracy_score(ensemble.predict(x1_train), y1_train))
print ("Accuracy - Test : ", sklearn.metrics.accuracy_score(ensemble.predict(x1_test), y1_test))


Predicting 2 layers
Processing layer-1             done | 00:00:00
Processing layer-2             done | 00:00:00
Predict complete                    | 00:00:00
Accuracy - Train :  1.0

Predicting 2 layers
Processing layer-1             done | 00:00:00
Processing layer-2             done | 00:00:00
Predict complete                    | 00:00:00
Accuracy - Test :  1.0


In [72]:
print("Fit data:\n%r" % ensemble.data)

Fit data:
                                   score-m  score-s  ft-m  ft-s  pt-m  pt-s
layer-1  logisticregression           0.99     0.01  0.37  0.09  0.00  0.00
layer-1  randomforestclassifier       0.99     0.01  0.63  0.14  0.02  0.00



As, The Accuracy on test and Training sets is 100%, which is greater than CNN model but I think model Overfits.